services:
  - type: web
    name: devsync-server
    env: node
    buildCommand: |
      cd backend
      npm install
    startCommand: |
      cd backend
      node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true
    healthCheckPath: /api/health
