services:
  - type: web
    name: devsync-server
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false  
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://devsync-backend-6fe4.onrender.com
      - key: FRONTEND_URL
        value: https://sayan-dev731.github.io/devsync-opensource
